version: '3'

services:
  php:
    container_name: comecome-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - comecome-network

  nginx:
    container_name: comecome-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - comecome-network

#   node:
#     container_name: comecome-node
#     build:
#       context: ./docker/node
#       dockerfile: Dockerfile.node
#     restart: unless-stopped
#     tty: true
#     volumes:
#       - ./:/var/www
#     networks:
#       - comecome-network

  mysql:
    container_name: comecome-mysql
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - comecome-data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - comecome-network
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  phpmyadmin:
    container_name: comecome-phpmyadmin
    image: phpmyadmin:5.2
    restart: always
    ports:
      - '8888:80'
    networks:
      - comecome-network
    environment:
      PMA_HOST: comecome-mysql
    depends_on:
      - mysql

  redis:
    container_name: comecome-redis
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    ports:
      - '6379:6379'

networks:
  comecome-network:
    driver: bridge

volumes:
  comecome-data:
    driver: local
